version: '3'

services: 
    product-service:
        build: ./product
        volumes:
            - ./product:/usr/src/app
        ports: 
            - 5001:80

    website:
        image: php:7.4.7-apache
        volumes:
            - ./website:/var/www/html
        ports:
            - 5000:80


    mongo:
        image: mongo:4.2.8

        restart: always
        ports:
            -50000:80
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

        depends_on: 
            - product-service
